### ISSUE TITLE
There is no way to use the tag emojis as anything other than the replaced tags

### ISSUE THREAD

**Issue by sergiu-paraschiv** [QuantGeekDev/lmaolang#26]
Me and my team were really prepared to switch to lmaolang but this right now is a blocker unfortunately 😢 

`🫦 List of reasons why I loooove 🫦🫦🫦 LMAO-lang 💀🫦 `
generates the following HTML:
`<h1> List of reasons why I loooove <h1><h1><h1> LMAO-lang </h1>`

I suggest introducing the `🪂` emoji, U+1FA82, to escape tags. My example would become:
`🫦 List of reasons why I loooove 🪂🫦🪂🫦🪂🫦 LMAO-lang 💀🫦 `
and, of course, escaping the escape emoji should be possible too.

If you cannot provide a solution for this by Monday then please let me know if you are open to community contributions.
Thank you very much!

**Comment by QuantGeekDev** [comment]
@sergiu-paraschiv 
> Me and my team were really prepared to switch to lmaolang but this right now is a blocker unfortunately 😢
> 
> `🫦 List of reasons why I loooove 🫦🫦🫦 LMAO-lang 💀🫦 ` generates the following HTML: `<h1> List of reasons why I loooove <h1><h1><h1> LMAO-lang </h1>`
> 
> I suggest introducing the `🪂` emoji, U+1FA82, to escape tags. My example would become: `🫦 List of reasons why I loooove 🪂🫦🪂🫦🪂🫦 LMAO-lang 💀🫦 ` and, of course, escaping the escape emoji should be possible too.
> 
> If you cannot provide a solution for this by Monday then please let me know if you are open to community contributions. Thank you very much!

Thank you for the input - I like this idea.  There are a lot of to-do's on the Trello, and we are very very open to community contributions - if you feel like adding this to the codebase, it would be greatly appreciated. But if not, I will eventually add this in as it is crucial (Emojis are MUST HAVE on my websites, personally). Without this, it will be hard to write the lmao-lang code for the lmao-lang documentation website... Can you imagine?

**Comment by sergiu-paraschiv** [comment]
Hi @QuantGeekDev 
Please check my PR that introduces the🪂 escape emoji 😺

**Comment by QuantGeekDev** [comment]
> Hi @QuantGeekDev Please check my PR that introduces the🪂 escape emoji 😺

It's beautiful. Merged
